name: Crypto Volume Scanner
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes, 24/7
  workflow_dispatch:  # Manual trigger
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install requests
    - name: Run Volume Scanner
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python scanner.py
